[tool.poetry]
name = "arson-guvi"
version = "0.1.0"
description = ""
authors = ["arson <youaregifted@myyahoo.com>"]
readme = "README.md"

[[tool.poetry.packages]]
include = "configs"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^3.0.5"
numpy = "^2.5.1"
openpyxl = "^3.1.5"
seaborn = "^0.13.2"
matplotlib = "^3.11.1"


[tool.poetry.group.dev.dependencies]
ipykernel = "^7.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
